### ISSUE TITLE
你好，我由于在飞桨社区找不到你的联系方式，所以一路查询到了此处，你的数据遥感影像超分辨率重建数据集我有一些问题想练下下你

### ISSUE THREAD

**Issue by xywxy** [kongdebug/nerf-paddle#1]
我去查询了下这个数据集，它包含21个场景类别，每个类别100张图像，总共2100张图像，请问你这里怎么会有6720+420=7140 / 2 = 3570 张呢？请问多余的是哪里的图片呀？

**Comment by kongdebug** [comment]
https://aistudio.baidu.com/aistudio/datasetdetail/129011/2

**Comment by kongdebug** [comment]
> 我去查询了下这个数据集，它包含21个场景类别，每个类别100张图像，总共2100张图像，请问你这里怎么会有6720+420=7140 / 2 = 3570 张呢？请问多余的是哪里的图片呀？

https://github.com/kongdebug/nerf-paddle/issues/1#issue-1244656595

**Comment by kongdebug** [comment]
> 我去查询了下这个数据集，它包含21个场景类别，每个类别100张图像，总共2100张图像，请问你这里怎么会有6720+420=7140 / 2 = 3570 张呢？请问多余的是哪里的图片呀？

https://aistudio.baidu.com/aistudio/datasetdetail/129011/2

**Comment by dream-in-night** [comment]
"想练下下你 " 😂

**Comment by kongdebug** [comment]
***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月7日(星期三) 上午9:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [kongdebug/nerf-paddle] 你好，我由于在飞桨社区找不到你的联系方式，所以一路查询到了此处，你的数据遥感影像超分辨率重建数据集我有一些问题想练下下你 (Issue #1)





 
"想练下下你 " 😂
